import type { Metadata } from "next";
import "./globals.css";
import ApolloWrapper from "@/components/ApolloWrapper";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Pre-Inspected Used Cars",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {




  return (
    <html lang="en" className="overflow-x-hidden ">
      <Head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" />
      </Head>
      <body className="bg-lightGray">
        <ApolloWrapper>
            {children}
        </ApolloWrapper>
       
      </body>
    </html>
  );
}
